sudo: required
services:
    - docker

before_install:
    - docker build -t jibinrajck/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true jibinrajck/react-test npm test

after_success: 
    - docker build -t jibinrajck/multi-client ./client
    - docker build -t jibinrajck/multi-nginx ./nginx
    - docker build -t jibinrajck/multi-server ./server
    - docker build -t jibinrajck/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push jibinrajck/multi-nginx
    - docker push jibinrajck/multi-server
    - docker push jibinrajck/multi-worker
    - docker push jibinrajck/multi-client